# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [master]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
     
    env:
     QWE: 333333333 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
           echo "Hello ${QWE+1} "
           echo "Hello $GITHUB_REPOSITORY_OWNER " 
      if: github.ref!='refs/heads/main' 
   
   

  grqwerty:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: greet

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: ls
