# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [master]
# A workflow run is made up of one or morejk jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  runs-on: ubuntu-latest
  services:
    # Label used to access the service container
    postgres:
      # Docker Hub image
      image: postgres
      # Provide the password for postgres
      env:
        POSTGRES_PASSWORD: postgres
      # Set health checks to wait until postgres has started
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
      ports:
        # Maps tcp port 5432 on service container to the host
        - 5432:5432

  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
     QWE: 333333333 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
           echo "Hello ${QWE+1} "
           echo "Hello $GITHUB_REPOSITORY_OWNER " 
#      if: GITHUB_REPOSITORY_OWNER='qwertyu'
   
   

  grqwerty:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: greet
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: ls
